# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a3b9fa43432776a90c15b302ddc17814"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "traya-checkout"
handle = "traya-checkout"

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_payment_customizations"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
dev_store_url = "traya-development-preview.myshopify.com"
